### ISSUE TITLE
Make into a jupyterlab extension

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#100]
A proposal for a rainy day https://github.com/jupyterlab/jupyterlab_launcher

**Comment by SimonBiggs** [comment]
Definitely will do. ScriptedForms originally was an app. I undid it so I could have a standalone version first for those without jupyterlab, but then also a jupyterlab app/extension.

It actually won't be too hard to pull it in.

**Comment by SimonBiggs** [comment]
Tracking this issue under https://github.com/SimonBiggs/scriptedforms/issues/161
