### ISSUE TITLE
Look into binder infrastructure

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#104]
I might be able to make a package that makes hosting of binders of ScriptedForms really simple. That would be great.

People shouldn't need a username and password to fill out a form. Binder might be the perfect fit for running scriptedform servers.

**Comment by robmarkcole** [comment]
You can also then have live examples right here on Github, see https://github.com/robmarkcole/Kalman-and-Bayesian-Filters-in-Python

**Comment by SimonBiggs** [comment]
We'll see. Don't get your hopes up :)

**Comment by SimonBiggs** [comment]
@robmarkcole this is doable. Both this and jupyterhub coming in a release soon near you :)

**Comment by robmarkcole** [comment]
Brilliant :-)
