### ISSUE TITLE
Implement ag-grid

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#106]
https://github.com/handsontable/angular-handsontable/blob/master/README.md

**Comment by SimonBiggs** [comment]
https://handsontable.com/features

**Comment by SimonBiggs** [comment]
@robmarkcole what do you think about this?

**Comment by robmarkcole** [comment]
Can you copy-paste into those tables?

**Comment by SimonBiggs** [comment]
I don't know...

**Comment by SimonBiggs** [comment]
They have interactive demos on their site. Give it a try? I'm on my mobile at the moment.

**Comment by robmarkcole** [comment]
https://docs.handsontable.com/0.36.0/CopyPaste.html?_ga=2.33149565.215781205.1519851621-1740677816.1519851621

**Comment by SimonBiggs** [comment]
I looked through the process tier, there was no copy paste on that tier.

**Comment by robmarkcole** [comment]
My personal inclination is to steer away from anything that isn't fully open source

**Comment by SimonBiggs** [comment]
Handsome tables CE has copy paste, and that is open source.

**Comment by SimonBiggs** [comment]
So what do you think? Worth giving it a shot?

**Comment by robmarkcole** [comment]
I think so. Tables are bread and butter so worth making them look decent

**Comment by SimonBiggs** [comment]
Initially I would aim to strip down as much as possible, including only the bare minimum. As time goes on we can work out what features should be enabled that don't make things too complex.

**Comment by robmarkcole** [comment]
Agreed. If people want a complex package those tools already exist. Beauty and simplicity should be the selling points of scriptedforms

**Comment by SimonBiggs** [comment]
Use ag-grid instead of handson table

Their first example at the following:

https://www.ag-grid.com/?utm_source=webpack&utm_medium=banner&utm_campaign=sponsorship

Is using material design, which fits in much nicer with the theme of the forms.

Here are some comparisons between differing grids:

https://github.com/AmitMY/grids

**Comment by SimonBiggs** [comment]
ag-grid looks absolutely amazing! ... okay, that's what I am going to use instead.

**Comment by SimonBiggs** [comment]
Ahh... copy/paste in ag-grid is enterprise only... @robmarkcole were you massively keen on the copy paste feature?

**Comment by robmarkcole** [comment]
Yes from my experience people will definitely want to copy-paste from excel sheets

**Comment by SimonBiggs** [comment]
Handsontables doesn't look like it handles printing necessarily well:

https://github.com/handsontable/handsontable/issues/2342

However ag-grid has an option that by default renders it ready for printing:

https://www.ag-grid.com/javascript-grid-for-print/

... I think unfortunately being able to print the table is more important than the copy/paste feature...

**Comment by robmarkcole** [comment]
I have to say we really want both

**Comment by SimonBiggs** [comment]
Another thought, have used xlwings before? If a particular form needs close interaction with excel, combining it with xlwings could be a perfect match. Even better than copy paste or API...

**Comment by robmarkcole** [comment]
I've used xlwings a bit. The only catch is people need python and it installed, so no good for sharing with non python colleagues. How do you proposed to integrate?

**Comment by SimonBiggs** [comment]
See #2

**Comment by robmarkcole** [comment]
@SimonBiggs another option for tables http://holoviews.org/user_guide/Tabular_Datasets.html

**Comment by SimonBiggs** [comment]
Could you try installing the jupyterlab bokeh extension and seeing if bokeh
works out of the box? You might get holoviews then as well...

**Comment by robmarkcole** [comment]
@SimonBiggs I would try at work but installing anything via a package manager is a right nightmare. If there was a way to bundle all the required dependencies into a .zip file that anyone could download without using a package manager that would be a real help

**Comment by SimonBiggs** [comment]
Sure. All good :) Let's not worry about that just yet.

**Comment by SimonBiggs** [comment]
erghh... ag-grid is not what I want to use.

I'll stick with the angular material grid. Will have to implement elements myself.
