### ISSUE TITLE
Have live documentation

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#107]

**Comment by robmarkcole** [comment]
Are the in development docs available? I would like to know which python packages are available by default - appears pandas, numpy..?

**Comment by SimonBiggs** [comment]
https://github.com/SimonBiggs/scriptedforms/blob/master/scriptedforms/src/services/session-start-code.ts

**Comment by SimonBiggs** [comment]
Live docs issue will be detailed within the following issue:

https://github.com/SimonBiggs/scriptedforms/issues/148
