### ISSUE TITLE
Take 0.6.1 for a spin

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#112]
Heya @robmarkcole,

Would you be able to take 0.6.1 for a spin. There are a few behind the scenes changes, and there is a new toolbar.

The template can't yet add to the toolbar, but print, refresh, and view source on pypi all should work.

**Comment by robmarkcole** [comment]
Looks good, although I would suggest opening the docs in a separate tab, and perhaps `docs` would be more instructive than the symbol you have now. 
Cheers 

![image](https://user-images.githubusercontent.com/11855322/36846149-6f0754dc-1d51-11e8-8b64-18a66d41ba3a.png)

**Comment by SimonBiggs** [comment]
I agree. I think it's high time to think of a ScriptedForms logo. And I'll
put that logo there and link it to scriptedforms.com.au opening in a new
tab.

**Comment by SimonBiggs** [comment]
https://github.com/SimonBiggs/scriptedforms/issues/114
