### ISSUE TITLE
Plots to fill page width

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#113]
Is it possible to set the default size of plots to be the width of the page? They look a bit puny

![image](https://user-images.githubusercontent.com/11855322/36854461-f7d6c236-1d68-11e8-9792-8807cf1c8517.png)

**Comment by SimonBiggs** [comment]
Write 

```python
plt.figure(figsize=(20,20))
plt.plot(data)
```

Scaling of the plot on the web interface side will make it look pixelated.

**Comment by robmarkcole** [comment]
Thinking more about it, we don't want to change the default figure size as this would mean people couldn't just copy paste from their existing notebooks

**Comment by SimonBiggs** [comment]
I could make it however that plots are centred...
