### ISSUE TITLE
Change the "source code" button

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#114]
Make a logo. Change the source code button to that logo. Make it go to scriptedforms.com.au. When the website is the docs make sure to mention in the tooltip 'ScripteForms documentation, installation instructions, and source code'

Make clicking the button open in a new tab.

**Comment by SimonBiggs** [comment]
Actually I think I know what you mean by "docs icon".

@robmarkcole do you mean something like this:

https://material.io/icons/#ic_chrome_reader_mode

And then just have that go to scriptedforms.com.au

What do you think?

**Comment by robmarkcole** [comment]
Yes, perfect!

**Comment by SimonBiggs** [comment]
Complete.
