### ISSUE TITLE
Make slider activate during movement

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#117]
This will aid the smooth "morphing" effect on plots.

**Comment by SimonBiggs** [comment]
Completed in https://github.com/SimonBiggs/scriptedforms/commit/8b3a0a76b1d5084d0a3a9bc463453e38432399df.

**Comment by SimonBiggs** [comment]
Heya @robmarkcole,

Would you be able to install the development version of master. I'd be keen for your feedback on the following slider:

![image](https://user-images.githubusercontent.com/6559099/36883594-912d1c0c-1e2f-11e8-8edb-f0f4475e1a68.png)

**Comment by robmarkcole** [comment]
Btw you don't appear to have a development branch?

**Comment by SimonBiggs** [comment]
Sorry, I worded that badly. I meant master. In a couple of weeks I'll be swapping over to doing all work on branches and merging them into master.

**Comment by SimonBiggs** [comment]
I won't worry about the phases. For now that presents the concept.
