### ISSUE TITLE
Updated readme screenshots

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#122]
@robmarkcole let me know if you have any feedback

**Comment by robmarkcole** [comment]
I would add a subheading to quickstart. Consider adding:

### Simple Plot
If you want to be a bit more adventurous...

**Comment by robmarkcole** [comment]
On another note your Github title is a bit busy - I would try get this (and the URL) on a single line:
<< Making GUIs easy for everyone on your team >> Quickly create live-update GUIs for Python packages using Markdown and a few custom HTML elements.

to

 Quickly create live-update GUIs for Python packages using Markdown and simple HTML elements.

**Comment by SimonBiggs** [comment]
kk :) doing both

**Comment by SimonBiggs** [comment]
Also version 0.6.2 is now out. If you could take it for a spin and let me know how it fares that'd be awesome.

**Comment by robmarkcole** [comment]
0.6.2 runs OK
