### ISSUE TITLE
Consider running a conversion over the file change paths list

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#130]
Might be worth running os.path.abspath on all of the paths. That will make the format consistent ... I think this needs to happen. That way a user could write in '../' and it will actually work.

It will also help a form that has been written on Linux work on Windows when the path delimiter changes.

**Comment by robmarkcole** [comment]
Im actually addressing an almost identical problem on Home-assistant [here](https://github.com/home-assistant/home-assistant/pull/12866), not sure if its a case study however

**Comment by SimonBiggs** [comment]
Fixed in https://github.com/SimonBiggs/scriptedforms/commit/3685cf470919103f7d2b2a3138e927efab3222c5
