### ISSUE TITLE
Remove rest API for now

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#138]
@robmarkcole does the filechange section cover the cases you were planning on using the rest API for?

If you can feasibly use features of ScriptedForms directly instead of the API I would prefer that. By having the API sit there when it is not currently being used, it is locking something in that might not be optimal.

My preference, remove the API, keep a record of how it was created bring it back at the moment when it is going to be heavily used. That way it can undergo changes at the time when people who are feeding back into the design of it are heavily using it. My primary preference is I would prefer to write the API when I am personally needing it, because then I will know what I need when I am trying to use it.

If we leave it as is, people will start using it, possibly not give feedback on pain points, and then I can't change it because it has been within the code base for a long time.

**Comment by SimonBiggs** [comment]
Also, until then, if you really need an API, jupyterlab already provides one... In fact, my API actually is just shortcuts to the current Jupyter API...

**Comment by robmarkcole** [comment]
OK if it is duplicating functionality then we should leave out until expressly required

**Comment by SimonBiggs** [comment]
Thanks @robmarkcole , the way I see it, all features of the current API can be replaced with the filechange section.

**Comment by robmarkcole** [comment]
Yes I've lost that issue, which number was it?

**Comment by SimonBiggs** [comment]
Sorry which issue?

**Comment by SimonBiggs** [comment]
I'll close the issue once I've actually done it :)

**Comment by robmarkcole** [comment]
The filewatcher instructions

**Comment by SimonBiggs** [comment]
#2 :)
