### ISSUE TITLE
Make the live docs run on mybinder

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#149]

**Comment by SimonBiggs** [comment]
@robmarkcole Thought you might be interested that there is now a mybinder link on the front readme (https://mybinder.org/v2/gh/SimonBiggs/scriptedforms-examples/master). Also, binder works with jupyterhub, so since ScriptedForms now works on mybinder, it should now also work on JupyterHub. :)

**Comment by robmarkcole** [comment]
@SimonBiggs great work! I've an initiative to setup a company wide jupyterhub and this will be a great way for us to share models internally. 
Getting familiar with Jupyter extensions is high on my list. Finishing off a couple of projects beforehand.
