### ISSUE TITLE
Watchdog file list in a table

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#182]
I have a use case which may require functionaltiy added. I want to use scriptedforms to capture a list of images saved during an experiment run. I will use a form to enter the experiment parameters (in my case camera exposure time etc) and I want the form to display a list of all the .jpg images saved in a folder. At the and of the experiment run I will post the paths of all saved .jpg to an external database. Thereore my request is: live updating table of all .jpg files in a folder. Is this possible?

**Comment by SimonBiggs** [comment]
Yup. Can definitely be done with the current set up.

Something like the following should work. I haven't tested it, just wrote it in here. But it should be close.

~~~markdown

<section-start>

```python
import os
from glob import glob
from IPython.display import display, Markdown

path_to_watch = '/a/path/here'
glob_string = os.path.join(path_to_watch, '*.jpg')
```

</section-start>

<section-filechange paths="[path_to_watch]">

```python
file_list = glob(glob_string)
markdown_string = '\n'.join([
    "* {}".format(file)
    for file in file_list
])
display(Markdown(markdown_string))
```

</section-filechange>

~~~

**Comment by robmarkcole** [comment]
With the same application in mind, is it possible to programatically display input text fields, in this case using the column headers from a database?

**Comment by SimonBiggs** [comment]
Yup, programmatically create a pandas dataframe and use the table variable. Would that work?

**Comment by robmarkcole** [comment]
Your example works nicely 

![image](https://user-images.githubusercontent.com/11855322/37918186-2d18cae4-3118-11e8-8fb8-797df11c1d14.png)

**Comment by SimonBiggs** [comment]
Good to hear :)
