### ISSUE TITLE
Inline option on button-sections

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#184]
I created the button below:

![image](https://user-images.githubusercontent.com/11855322/37918979-835569b0-311a-11e8-9cc2-b2a6fe02f6d6.png)

Can I suggest that buttons should be left oriented, i.e. appear on the left of the screen, in this case under the section title?

Another suggestion, is it possible to have a pop-up box with a message that can be determined by the python code? In my example, the message would be 'File saved successfully' if there are no exceptions in a `try, except`

**Comment by SimonBiggs** [comment]
With regards to the popup did you want something like the following?
https://material.angular.io/components/snack-bar/overview.

If you could throw that in another issue that'd be great.

With the button layout, you can edit that yourself already. Create a <style> tag, and using "inspect element" within your browser find out the css class of the browser. From there you can override the right alignment.

Unfortunately for that element I have used inline styling which makes it a bit harder to override. That's an easy fix for me to do though.

**Comment by robmarkcole** [comment]
OK created https://github.com/SimonBiggs/scriptedforms/issues/188

**Comment by SimonBiggs** [comment]
I still want to make it so you can move the button around :)

**Comment by SimonBiggs** [comment]
Hi @robmarkcole,

I have created an 'inline' property for buttons. Use it like the following:

```html
<section-button inline>
```

It is currently only working on the dev install.
