### ISSUE TITLE
Remove margin before output area. Make Markdown font be Roboto within output area.

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#185]
My apologies if this is documented already, I didn't find it. 

I have a python variable (`path_to_watch = os.path.join(os.getcwd(), 'test_folder')` )which I wish to display within a body of Markdown text - is this possible? I was hoping to do the following:

```markdown
# Folder monitor
Watching folder Markdown(path_to_watch) for changes.
```

**Comment by SimonBiggs** [comment]
First thing you're probably best off using `path_to_watch = os.path.abspath('test_folder')`.

As long as the following code has been run `from IPython.display import display, Markdown` them you will be able to run the following:

```python
markdown_string = """
Watching folder {} for changes.
""".format(path_to_watch)
display(Markdown (markdown_string))
```

**Comment by robmarkcole** [comment]
Thanks @SimonBiggs that puts the string in the python section (below), but it's not possible to put the string in the Markdown section?

![image](https://user-images.githubusercontent.com/11855322/37980608-67c7a5d6-31e3-11e8-85c6-f1df643f3608.png)

**Comment by SimonBiggs** [comment]
Actually there is a way... Your could write the following in line with your other text:

<code class="language-python">display(Markdown(your_variable))</code>

I'm not sure how it would style though.

**Comment by SimonBiggs** [comment]
Also, would something like the following be a way to solve your issue?

https://github.com/SimonBiggs/scriptedforms/issues/196

**Comment by SimonBiggs** [comment]
Hi @robmarkcole 

I have removed the margin in the dev version with https://github.com/SimonBiggs/scriptedforms/commit/aed35b2fb40f81994f60407cfc5cf7225977e77c

Let me know if that solves this issue.
