### ISSUE TITLE
View tables with non-numerical fields

### ISSUE THREAD

**Issue by OxygenLithium** [SimonBiggs/scriptedforms#190]
Hi,

At the moment it seems that tables only support numerical fields. Would it be possible to have them display text when reading from a database?

In addition, an option to view tables without being able to edit them would be nice too.

![image](https://user-images.githubusercontent.com/36341776/38085265-c2046934-3347-11e8-90b4-1162b389ef49.png)

**Comment by SimonBiggs** [comment]
I agree on both points. What I need to to is implement ag-grid which is tracked at the following issue:

https://github.com/SimonBiggs/scriptedforms/issues/106

It has a great material design option. It will fit very well with ScriptedForms. Once I've implemented ag-grid I just need to map the Python variables across.

It did keep getting bumped further down my list, but I can put it into high priority if you would like?

**Comment by OxygenLithium** [comment]
Seems like a key feature for forms, so would be useful having this as higher priority

Cheers for the rapid responses!

**Comment by SimonBiggs** [comment]
Yeah. It is a key feature. At the moment I only have a few hours a week to spend working on this so I need to pick what I work on carefully. In about three months we will seriously be ramping up our usage of ScriptedForms at work meaning not just home time will be dedicated to these sorts of things.

Im looking for people who can work on ScriptedForms with me if you know anyone?

**Comment by SimonBiggs** [comment]
Alright, so I looked into ag-grid. It was not what I thought it was going to be. So I'm going to be sticking to angular material grid.

For now would it be enough if there was just string and number? As in, just implement string as well as number. I can deal with booleans at a later date.

And then maybe I can add a parameter "column-lock" or something, accepts a python list, if values in the list match a column then that column is read only. 

What are your thoughts?

**Comment by SimonBiggs** [comment]
@OxygenLithium Alrighty, so the development version of ScriptedForms now accepts each of the pandas table json schema typese:

https://github.com/pandas-dev/pandas/blob/a00154dcfe5057cb3fd86653172e74b6893e337d/pandas/io/json/table_schema.py#L32-L60

There are still a few bugs with it though. If you could take it for a spin and see what bugs you can find. See if we can squash em ready for a release.
