### ISSUE TITLE
Text fields retaining value (only visually) on kernel restart

### ISSUE THREAD

**Issue by OxygenLithium** [SimonBiggs/scriptedforms#191]
When restarting the Jupyter Kernel, text fields remain filled in but python cannot detect the value.

E.g. in this instance, Python says it cannot find a value for 'User' unless I click on the field, edit a character and then re-run the python script with a button.

![image](https://user-images.githubusercontent.com/36341776/38085435-69ed548a-3348-11e8-991d-e352dea2c3d7.png)

**Comment by SimonBiggs** [comment]
Yup, this should be an easy fix. I'll schedule that for the next release.

**Comment by OxygenLithium** [comment]
Great, happy to help. Looks like this could become a unique and incredibly useful tool

**Comment by SimonBiggs** [comment]
I really hope so :). We have already found it quite useful at work. As it becomes more polished that should only increase.

**Comment by SimonBiggs** [comment]
Fixed in https://github.com/SimonBiggs/scriptedforms/commit/0d2fdc931e423b5285bb8c9f3acc1f2c261491e3
