### ISSUE TITLE
Text field placeholders

### ISSUE THREAD

**Issue by OxygenLithium** [SimonBiggs/scriptedforms#192]
Ability to start up a scriptedform with text boxes pre-filled with greyed out text.
Once text is entered in to the text box, the greyed out text disappears.
Similar to HTML5 text placeholders.

**Comment by SimonBiggs** [comment]
Yup, this should be easy I think. I'll set this for next release also.

**Comment by OxygenLithium** [comment]
I'll have a look at the dev version tomorrow :)
I think label makes much more sense and name should be phased out as you suggested
