### ISSUE TITLE
Make a watchdog section

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#2]
Have the contents of a watchdog section rerun whenever there is a change in any of the files within the directory provided to the section.

**Comment by SimonBiggs** [comment]
@robmarkcole so picture this. A "file change" section. It runs whenever a named file changes that is on disk. Let the file be an excel spreadsheet that is on a network drive, that both the scriptedforms server and the user can access. Everytime that excel spreadsheet changes, that scriptedform section automatically runs...

**Comment by SimonBiggs** [comment]
Then use pandas, or xlwings within scriptedforms to pull the data from excel and do whatever you want...

**Comment by SimonBiggs** [comment]
The only feature I would need to add is this one highlighted by this issue. It's not too hard a feature to implement. I could make it high priority if you would find this workflow helpful.

**Comment by SimonBiggs** [comment]
The only thing I would add is this watchdog/file change section. The user can import xlwings if they desire. I would probably also add an example where the file is say a CSV file, and changing the CSV file updates the table within scriptedforms.

**Comment by SimonBiggs** [comment]
Let me know if you're keen on this feature sooner rather than later and if so I can prioritise it appropriately.

**Comment by robmarkcole** [comment]
I can immediately see the use case in both medical physics and elsewhere, so I would prioritise. I'm happy to do some demo forms

**Comment by SimonBiggs** [comment]
As part of this feature the file path should be able to be defined with python written into the parameter. That way workflows such as a user typing a path into a string variable and then having the watchdog section be based upon that path.

**Comment by robmarkcole** [comment]
You could define it as a variable in the setup 
PATH = '/somefolder'

**Comment by SimonBiggs** [comment]
It will look like:

~~~markdown
<section-filechange paths="['/a/path/here/file.csv', '/a/path/to/whole/directory']" recursive>

```python
code here
```

</section-filechange>
~~~

The "paths" parameter takes a python list. Recursive is an optional parameter which will tell watchdog to search all subdirectories within a given directory. Paths can be a file or a directory.

**Comment by robmarkcole** [comment]
The looks powerful but I was thinking it could be simpler:

In setup
```python
MASTER_PATH = "/a/path/here/file.csv"
```

Then:
```
<section-filechange master_file=MASTER_PATH, file_2 = "/some_other_path/file2.csv">

python.compares.func(master_file, file_2)
```

**Comment by SimonBiggs** [comment]
You could just do the following:

In setup:

```python
MASTER_PATH = "/a/path/here/file.csv"
file_2 = "/some_other_path/file2.csv"
paths = [MASTER_PATH, file_2]
```

Then the section looks like:

```html
<section-filechange paths="paths">
etc...
```

**Comment by SimonBiggs** [comment]
Which is using the same implementation as I just described before...

**Comment by robmarkcole** [comment]
However `paths` would always have to be a list, even if I only want to watch a single file, which seems like the most frequent use case. Could also have `path`:

```
<section-filechange path = "/some_other_path/file2.csv">
```

**Comment by SimonBiggs** [comment]
The issue there is, if you want to also enable the following:

```markdown
<section-filechange path="a_python_variable">
```

You would have to distinguish between a variable name and a string by using single quotes like so:

```markdown
<section-filechange path=" '/a/path/string' ">
```

Having to put quotes inside quotes feels clunky to me, and I think people would often get it wrong causing Python to throw syntax errors.

My thought is if I force it to always be a list at least it is obvious what is going on:

```markdown
<section-filechange path="['/a/path/string']">
```

**Comment by robmarkcole** [comment]
OK, I am on board now. Whoever is editing the scriptedform is going to know about lists.

**Comment by SimonBiggs** [comment]
The extra benefit, is this also aligns with how dropdowns are defined.

**Comment by SimonBiggs** [comment]
By the way, this is going to do a bit of a rework of the implementation of the API. If you do get a chance to throw a few API tests together that would be epic.

**Comment by robmarkcole** [comment]
API tests on my radar

**Comment by SimonBiggs** [comment]
Completed within https://github.com/SimonBiggs/scriptedforms/commit/da1ad6993e84d554b5b32e1d1e3f635357f78b14

Because of the following issue, there are some struggles with tables:

https://github.com/SimonBiggs/scriptedforms/issues/75

For example, a table heading must be defined, and must be strings, and the content must be numbers. It ends up with quite a brittle result when live updating from a csv file.

It works, but I think https://github.com/SimonBiggs/scriptedforms/issues/106 needs to be bumped up in priority to be able to realistically use have a live update csv within the scriptedform.

@robmarkcole could you download and install the latest master branch and see what issues arise with the new `<section-filechange>`.

Hope you enjoy playing with it :). It is kinda cool :).

**Comment by SimonBiggs** [comment]
Raise any bugs with the `<section-filechange>` in a new issue so they can be tracked separately from here.
