### ISSUE TITLE
404 on bundle.js

### ISSUE THREAD

**Issue by dsblank** [SimonBiggs/scriptedforms#21]
I think I did the minimal instructions (and tried other things) but I only get this 404 error, and nothing shows in the browser. Do I need something else?

```
$ example
[I 09:01:40.093 ScriptedForms] Serving notebooks from local directory: /home/dblank/scriptedforms/example/example
[I 09:01:40.093 ScriptedForms] 0 active kernels
[I 09:01:40.093 ScriptedForms] The Jupyter Notebook is running at:
[I 09:01:40.093 ScriptedForms] http://localhost:8888/?token=fc499dc515204a49bb321f2e732b48c6f0ed3d3231418c8e
[I 09:01:40.093 ScriptedForms] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:01:40.094 ScriptedForms] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=fc499dc515204a49bb321f2e732b48c6f0ed3d3231418c8e
[I 09:01:40.431 ScriptedForms] Accepting one-time-token-authenticated connection from 127.0.0.1
[1562:1601:0209/090140.466870:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
Created new window in existing browser session.
[W 09:01:40.661 ScriptedForms] 404 GET /scriptedforms/bundle.js (127.0.0.1) 132.64ms referer=http://localhost:8888/scriptedforms/simple.md?token=7c078939b25d0b9e67911e95f6ee070598919e530fb88445
```

**Comment by SimonBiggs** [comment]
Did you install via pypi or the github repo?

**Comment by SimonBiggs** [comment]
If I have guessed the issue correctly does this new part of the readme help?

https://github.com/SimonBiggs/scriptedforms/blob/master/README.md#development-build

**Comment by dsblank** [comment]
Indeed that worked! Here are the full instructions on a new Ubuntu:

```
sudo apt install curl
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
cd scriptedforms/scriptedforms
yarn
yarn build
cd ..
pip install . -U --user
cd example/
pip install . -U --user
example
```
I've been wanting to start building on top of the Jupyter infrastructure, and this looks like a good step to help. Thanks so much for sharing!

**Comment by SimonBiggs** [comment]
Wonderful to hear :) It has been a joy diving into the Jupyter infrastructure. You might be interested in the following example:

https://github.com/jupyterlab/jupyterlab/tree/master/packages/services/examples/typescript-browser-with-output

I spun that example out of this project quite early on with the aim to try and produce a minimal example for jupyterlab-services.

Let me know if you need any more pointers :).

Also if there is a part of my code that isn't making much sense let me know and I'll see what I can do to make it more understandable.

**Comment by dsblank** [comment]
Thanks! Yes, JupyterLab is really what I would like to build on, so I'll take a look at that.

**Comment by SimonBiggs** [comment]
The JupyterLab team are very helpful. You might find https://gitter.im/jupyterlab/jupyterlab a good place to ask small quick questions as they come up.
