### ISSUE TITLE
See errors in <section-start>

### ISSUE THREAD

**Issue by OxygenLithium** [SimonBiggs/scriptedforms#217]
A way to see if there is an error in python code run in the <section-start> </section-start> section would be very useful.

**Comment by SimonBiggs** [comment]
Section start does have its own output area. I imagine any error should display... Does it not?

**Comment by SimonBiggs** [comment]
Eg does `raise Exception('boo')` display something?

**Comment by OxygenLithium** [comment]
I've noticed that sometimes errors aren't displayed. I will try to find an example, but I've had situations where I have an error but no error message. I then copy the python code from the section-start to another section and then the error code is visible.

**Comment by SimonBiggs** [comment]
Okay, I need to sort that out. I was thinking of putting an ipython console
collapsed and docked to the side of the screen.

It would make debugging much easier... The idea is if ever an error occurs
then that console window will pop open.

Do let me know if you can find the cases when that happens. One I know of
is errors within conditional components.

**Comment by OxygenLithium** [comment]
I like that idea.
When you need it it would be available, then when you release a form the debugging info can be hidden

**Comment by SimonBiggs** [comment]
See #216
