### ISSUE TITLE
Portable scriptedforms batch file not working

### ISSUE THREAD

**Issue by OxygenLithium** [SimonBiggs/scriptedforms#221]
Version: 0.9 & 0.8
Windows 7 

Running the batch file gives the error 'Windows cannot find '-m'. Make sure you typed the name correctly, and then try again.'

Removing start from the beginning of the script seems to fix this issue.

**Comment by SimonBiggs** [comment]
That is very odd. Does the portable version for 0.7.1 work?

**Comment by OxygenLithium** [comment]
Fairly sure it did work in 0.7.1...
I believe (may be wrong), that the 0.7.1 batch file doesn't have the start at the beginning?

**Comment by SimonBiggs** [comment]
Thanks for reporting this. I have deleted the portable version off of 0.8.0, and have fixed the version uploaded to 0.9.0.

Cheers
