### ISSUE TITLE
[Experimental idea] Create a <jinja-template> component

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#246]
Alright, so, to help begin addressing the following issues:

 * https://github.com/SimonBiggs/scriptedforms/issues/242
 * https://github.com/SimonBiggs/scriptedforms/issues/241
 * https://github.com/SimonBiggs/scriptedforms/issues/240
 * https://github.com/SimonBiggs/scriptedforms/issues/234
 * https://github.com/SimonBiggs/scriptedforms/issues/219
 * https://github.com/SimonBiggs/scriptedforms/issues/196
 * https://github.com/SimonBiggs/scriptedforms/issues/177
 * https://github.com/SimonBiggs/scriptedforms/issues/148

I will be attempting to create a `<jinja>` component. The idea/hope is that it will be able to work as so:

~~~markdown
<section-start>

```python
tables = {
    'first_table': pd.DataFrame(data=[1, 2, 3]),
    'second_table': pd.DataFrame(data=[4, 5, 6])
}

a_python_dictionary = {
    a_title: 'foo',
    image_srcs: ['a', 'few', 'sources'],
    another_title: 'boo',
    tables: tables,
    some_text: None
}
```

</section-start>

<variable-string>a_python_dictionary['some_text']</variable_string>

<jinja-template context="a_python_dictionary">

## {{ a_title }}

{% if some_text is not None %}
This text only displays if the variable string has been written in
<variable-tick>cant_see_me_until_string_is_written_in</variable-tick>
{% endif %}

{% for item in image_srcs %}
<img src="{{ item }}">
{% endfor %}

## {{ another_title  }}

{% for a_table_key in list(tables.keys()) %}
<variable-table>tables['{{ a_table_key }}']</variable-table>
{% endfor %}

</jinja-template>
~~~

**Comment by SimonBiggs** [comment]
A key issue with the implementation of this will be the fact that the html being rendered will be flexible. Previously if the html/markdown ever changed it was only because the file itself changed. This was coped with by refreshing the whole form.

A form refresh everytime the jinja template updates won't work. Therefore I need to decouple form component initialisation from the page loading sequence. This will be quite a refactor. This refactor will however help for a range of outstanding issues.

**Comment by SimonBiggs** [comment]
@OxygenLithium @robmarkcole any thoughts on this idea?

**Comment by robmarkcole** [comment]
What is the use case?

**Comment by SimonBiggs** [comment]
It is for advanced use cases. Not expected to be used in basic scenarios.

It makes what is displayed on the screen be significantly more flexible. For example, certain parts of the form can be conditionally displayed. Other parts of the form can be repeated as needed.

Forms could start quite sparse and then have the content of the form that is displayed on the screen grow conditionally depending on user input.

If this is a good idea, and if after implementing it it seems to work well, then I shall expand to refactoring the form structure also be a jinja template. The default one will be used as standard, however the template used by scriptedforms will be able to be swapped out. I can then use these templating options to customise scriptedforms into a documentation layout.

So instead of locking the layout away and making it rigid, I will be exposing the form layout and styling as a overridable jinja template.

**Comment by robmarkcole** [comment]
Understood, I can certainly see the benefits of this approach, so long as the basic usage maintains the currently simplicity

**Comment by OxygenLithium** [comment]
I really like this idea. How would someone use jinja to change the colour of a button for instance? Would it be that the user can define the colour in Python and then that variable is input into the HTML?

**Comment by SimonBiggs** [comment]
I've actually been thinking further about this. And I think what you've been keen on is actually something a bit different.

I think what you really want is top level access to the css. And I think I've worked out how to do it.

I should be able to also make that cover button color etc. I'll keep you posted.

**Comment by SimonBiggs** [comment]
Won't implement Jinja2 something like this feature will still be implemented however. Just not like this.
