### ISSUE TITLE
ipysheet

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#253]
Could be of interest 

https://github.com/QuantStack/ipysheet

**Comment by SimonBiggs** [comment]
Interesting I'll have a look. Does it work in JupyterLab?

**Comment by robmarkcole** [comment]
I'd say https://github.com/SimonBiggs/scriptedforms/issues/260 closes this

**Comment by SimonBiggs** [comment]
Yup, sounds good to me.
