### ISSUE TITLE
Jupyter server extension 404

### ISSUE THREAD

**Issue by RussellGrew** [SimonBiggs/scriptedforms#302]
Thanks for making this great library available. 

I found some commented out advice in the readme markdown. I wanted to confirm if it is still current.

The code below works but when I visit the URL, having modified the example below to point to a markdown file I get a 404 error. 

```
jupyter serverextension enable --py scriptedforms
jupyter notebook --NotebookApp.default_url=/scriptedforms/use/quick-start.md
``` 
It seems to be installed ok when I list the server extensions
```
    scriptedforms  enabled 
    - Validating...
      scriptedforms 0.10.1 OK
```
The usual Jupyter notebook interface loads fine. As does running scriptedforms directly on a markdown file.

I hope to make scriptedforms available for others and think this means I require the above and JupyterHub. Note that I am using the pip package and have not cloned git.

Any advice is appreciated.

**Comment by SimonBiggs** [comment]
Hi @RussellGrew,

The following three steps work for me. Do these work for you?

```bash
pip install scriptedforms
echo "# Hello World" > test.md
jupyter notebook --NotebookApp.default_url=/scriptedforms/use/test.md
```

Cheers,

Simon

**Comment by RussellGrew** [comment]
Hi Simon,

Thanks for that prompt response. 

I see my problem now.

I am new to Jupyter and thought `/scriptedforms/use` in the url referred to a path on disk. In your example I have been

```
jupyter notebook --NotebookApp.default_url=test.md
```

It works perfectly now.

Cheers.

**Comment by SimonBiggs** [comment]
Awesome :) All good :). Glad to help. Let me know how it goes.

I actually wanted to make a JupyterHub docker image that runs scriptedforms so that people can begin right away with a shared server. Never got around to it though...

**Comment by RussellGrew** [comment]
Is there a trick to making it work inside JupyterHub? I figure you have this in hand in order to be deployed on mybinder?

I have been reading #59 and #241 but don't seem to be able to make it happen.

Good luck with the Docker image. I possibly almost have a crude one here but without the requisite Postgres and mount points you envisioned. 

Thanks again.

**Comment by SimonBiggs** [comment]
That's okay. Anything you might have would be better than nothing. It'd be
a good start. Did you want to make a pull request?

Here is the mybinder repo if that helps:

https://github.com/SimonBiggs/scriptedforms-examples

**Comment by RussellGrew** [comment]
I very much cheated and started at
```
docker run -p 8000:8000 -d --name jupyterhub jupyterhub/jupyterhub jupyterhub
```
and did some upgrades in the shell. If I get around to doing something more scripted I will be in touch. 

Presently I have jupyterhub running outside docker with conda. I just installed jupyter-lab and then rebuilt it (on its recommendation) but am not getting anywhere. If you didn't do anything additional with your mybinder setup I will keep pecking away at this when time allows.

Thanks.
