### ISSUE TITLE
Error running the example

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#57]
On running [the example](https://github.com/SimonBiggs/scriptedforms/tree/master/example) on my personal machine (full admin rights, mac), I receive the following error:

```
Successfully installed example
Robins-MacBook-Air:example robincole$ example
[I 05:55:00.777 ScriptedForms] The port 8888 is already in use, trying another port.
[I 05:55:00.795 ScriptedForms] Serving notebooks from local directory: /Users/robincole/Documents/Github/scriptedforms/example/example
[I 05:55:00.795 ScriptedForms] 0 active kernels
[I 05:55:00.795 ScriptedForms] The Jupyter Notebook is running at:
[I 05:55:00.795 ScriptedForms] http://localhost:8889/?token=8ef039a89a804db418f7edfe79a66c430d7d4e8979d66e6f
[I 05:55:00.795 ScriptedForms] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 05:55:00.797 ScriptedForms]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=8ef039a89a804db418f7edfe79a66c430d7d4e8979d66e6f
[W 05:55:02.075 ScriptedForms] Forbidden
[W 05:55:02.075 ScriptedForms] 403 GET /api/kernelspecs?1519019702071 (::1) 1.77ms referer=http://localhost:8889/scriptedforms/simple.md?token=096fa697edd369cdb6cdb6990ebd2a8494468d37c71b4531
[W 05:55:02.293 ScriptedForms] Forbidden
[W 05:55:02.294 ScriptedForms] 403 GET /api/sessions?1519019702291 (::1) 0.83ms referer=http://localhost:8889/scriptedforms/simple.md?token=096fa697edd369cdb6cdb6990ebd2a8494468d37c71b4531
[W 05:55:02.485 ScriptedForms] 403 POST /api/sessions?1519019702482 (::1): '_xsrf' argument missing from POST
[W 05:55:02.486 ScriptedForms] '_xsrf' argument missing from POST
[W 05:55:02.486 ScriptedForms] 403 POST /api/sessions?1519019702482 (::1) 1.32ms referer=http://localhost:8889/scriptedforms/simple.md?token=096fa697edd369cdb6cdb6990ebd2a8494468d37c71b4531
[W 05:55:12.080 ScriptedForms] Forbidden
```

And see:
![image](https://user-images.githubusercontent.com/11855322/36364082-dddf5532-1539-11e8-9e7d-ba8e9d756576.png)

**Comment by SimonBiggs** [comment]
What version of jupyter notebook server are you running?

**Comment by robmarkcole** [comment]
jupyter                   1.0.0            
jupyter_client            5.1.0           
jupyter_console           5.2.0            
jupyter_core              4.3.0            
jupyterlab                0.27.0

**Comment by robmarkcole** [comment]
notebook                  5.2.2

**Comment by SimonBiggs** [comment]
Yup, I can replicate that error with notebook 5.2.2. Thanks for the report. Can you run:

`pip uninstall notebook && pip install notebook`

**Comment by robmarkcole** [comment]
OK issue closed with notebook 5.4.0

**Comment by SimonBiggs** [comment]
Thanks Robin :). I just released scriptedforms 0.5.3 which now forces notebook server to be >= 5.3

**Comment by SimonBiggs** [comment]
By the way. This project was mostly born out of thinking what a jupyter based interface to QATrack+ might look like.

**Comment by robmarkcole** [comment]
That’s great to know! Can think of many uses for this and will take for a spin at my current employer where I am designing satellites within a large collaborative team :)

**Comment by SimonBiggs** [comment]
Ooooo who is that with? That sounds awesome :)

**Comment by robmarkcole** [comment]
https://www.sstl.co.uk/

**Comment by SimonBiggs** [comment]
That looks like a very nice place to work :)
