### ISSUE TITLE
Convert scriptedforms into a jupyter notebook server extension

### ISSUE THREAD

**Issue by SimonBiggs** [SimonBiggs/scriptedforms#59]

**Comment by SimonBiggs** [comment]
Heya @robmarkcole this is now complete. I have created a new release 0.5.8 which now installs itself as a notebook extension.

Install it via `pip install scriptedforms --upgrade`.

If scriptedforms is installed then any jupyterhub instance should be able to navigate to `/scriptedforms/form-name.md` and it will display a scripted form.

**Comment by SimonBiggs** [comment]
Please take version 0.5.8 for a spin and let me know if it works with the jupyterhub :)

**Comment by robmarkcole** [comment]
Do I need to configure jupyterhub somehow? seeing 
![image](https://user-images.githubusercontent.com/11855322/36693650-e34fc240-1b33-11e8-809c-1139c8f5b768.png)

**Comment by SimonBiggs** [comment]
You need to replace the "edit", and you need to have run scriptedforms at least once onthat machine.

But I just realised by changing the url like that there might be some small assumptions that are broken. I'll set up a jupyterhub instance and aim to iron out issues tonight.

**Comment by SimonBiggs** [comment]
So after user/robincole/scriptedforms etc...

**Comment by robmarkcole** [comment]
On running scripted forms:
```
Robins-MacBook-Air:example robincole$ scriptedforms example.py
Traceback (most recent call last):
  File "/anaconda3/bin/scriptedforms", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms/scriptedforms.py", line 80, in main
    load(args.filepath, args)
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms/scriptedforms.py", line 51, in load
    install_jupyter_server_extension()
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms/_install_jupyter_server_extension.py", line 13, in install_jupyter_server_extension
    with open(config_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/robincole/.jupyter/jupyter_notebook_config.json'
```

**Comment by robmarkcole** [comment]
With 5.13 I'm seeing the following, which isn't what I'm expecting(?):

![image](https://user-images.githubusercontent.com/11855322/36715027-60865bb8-1b8c-11e8-9f03-874d6307fdbb.png)

**Comment by SimonBiggs** [comment]
That there is the jupyterlab interface. Can you copy the detailed.md file to the home directory of the server and then navigate to localhost:8888/scriptedforms/detailed.md

**Comment by robmarkcole** [comment]
OK working 

![image](https://user-images.githubusercontent.com/11855322/36716319-d7224cdc-1b91-11e8-8308-253cea96a0d5.png)

**Comment by SimonBiggs** [comment]
Awesome :) How about with jupyterhub?

**Comment by robmarkcole** [comment]
What should the url be? 

![image](https://user-images.githubusercontent.com/11855322/36716927-f9121b2c-1b93-11e8-9010-d807b1d883bc.png)

**Comment by SimonBiggs** [comment]
Running something like the following will take you straight there:

`jupyter notebook --NotebookApp.default_url=/scriptedforms/robin.md`

**Comment by SimonBiggs** [comment]
Not with the hub though. I'll need to have a play with jupyterhub.

**Comment by SimonBiggs** [comment]
Maybe you have a play to, let me know how you go.
