### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#76]
Currently none exists.
Cheers

**Comment by SimonBiggs** [comment]
You just want a requirements.txt as a declaration of what version I know work? Is that correct?

**Comment by robmarkcole** [comment]
Yes correct 👍

**Comment by SimonBiggs** [comment]
Fixed in https://github.com/SimonBiggs/scriptedforms/commit/83dff53e92b1b61332205914495bf5a9824fd03c

By the way, was there a main reason you were after the requirements.txt?

**Comment by robmarkcole** [comment]
I like to be able to quickly check the requirements

**Comment by SimonBiggs** [comment]
This is probably what you're really after then:

https://github.com/SimonBiggs/scriptedforms/blob/master/setup.py#L35-L41

**Comment by robmarkcole** [comment]
Yes it’s true the dependencies are in there. I think you can auto Gen requirements.txt

**Comment by SimonBiggs** [comment]
I made a requirements.txt, I just made it by installing scriptedforms in a virtual environment and then running pip freeze.

**Comment by SimonBiggs** [comment]
Also, let me know if there's something you'd like improved. I'm keen to make this package as easy to use as it can be :)

**Comment by robmarkcole** [comment]
Will do, but was unable to install at work due to dependencies

**Comment by SimonBiggs** [comment]
Oh? Which ones?

**Comment by SimonBiggs** [comment]
Would virtualenv do the trick?

**Comment by robmarkcole** [comment]
Numpy needs upgrading, and is on the C, so needs an admin password. The corporate firewall makes all installs a manual process too. However I think venv is the way to go 👍

**Comment by SimonBiggs** [comment]
The main issue is probably the Python 3.5 requirement. Do you have at least Python 3.5?

**Comment by SimonBiggs** [comment]
Anaconda Python can be installed in user space without admin privileges... That might be a good way to go?

**Comment by robmarkcole** [comment]
Yes I think that’s corrrect. IT installed my current install I recall

**Comment by SimonBiggs** [comment]
For now, I am going to remove the requirements.txt. I don't want to have to maintain it.
