### ISSUE TITLE
Missing requirements? 

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#80]
On running `python setup.py install `the following appear to be missing:

IPython
jupyter_client

**Comment by SimonBiggs** [comment]
Well I figure I depend upon the notebook server and you're not supposed to put sub dependencies within the setup.py. I don't directly depend upon IPython or jupyter_client. jupyter_client comes through depending on notebook:

https://github.com/jupyter/notebook/blob/master/setup.py#L79-L91

And IPython comes through ipykernel which notebook depends upon:

https://github.com/ipython/ipykernel/blob/master/setup.py#L83-L88

So, strictly I should not need to, nor should I be putting those dependencies within my own setup.py.

**Comment by SimonBiggs** [comment]
It is odd that those dependencies were missing.

**Comment by SimonBiggs** [comment]
Is it okay to close this issue now?
