### ISSUE TITLE
Tool to generate markdown files from python 

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#85]
I think it would be nice to be able to split out the python functions into their own .py files, then run a script to generate the .md files - or have them importd into the .md somehow. This way unit tests etc can be run on the python functions, and there is no danger of a copy-paste error leading to problems. 
An alternative approach would be to convert a jupyter notebook into the .md file, and use imports as normal.

**Comment by SimonBiggs** [comment]
Check out the following file:

https://raw.githubusercontent.com/SimonBiggs/scriptedforms/master/example/example/simple.md

That's demonstrating part of what you're talking about. You can just use python's ability to import files in the same directory as if they were modules.

**Comment by SimonBiggs** [comment]
A well designed package will have the lionshare of the code in .py files as functions and then import those modules/functions within a start section.

**Comment by robmarkcole** [comment]
OK sure. I was wondering if it was possible for someone to just create a jupyter notebook, download as .md, then run a script to put it in the correct format for scripted forms?

**Comment by SimonBiggs** [comment]
How would you put buttons in, how would you decide which sections were live sections, how would you put variables in?

**Comment by SimonBiggs** [comment]
From what I gather the process might be, download as a markdown file, then put in the relevant scriptedforms logic. Which is sort of where it's at at the moment

**Comment by robmarkcole** [comment]
I don't know if it would be possible to create an [custom ipython magic command](https://ipython.org/ipython-doc/3/config/custommagics.html) to insert the scriptedforms logic? Probably just replacing one issue with another so feel free to close this down

**Comment by SimonBiggs** [comment]
By using %aimport and %autoreload you are in the position that any code produced in your .py files automatically reimport as you update them. That way you could use %aimport within your notebook and move your functions from the notebook into a python file. Rerunning the notebook with the functions removed and instead imported from the python file.

Then once you've fully converted over to .py, then you can just import them into the scripted form. If you use the same functions from the same .py file in your notebook as the scriptedforms you know they will work the same.

Also, do use Visual Studio Code? It's python linting is exceptionally helpful for picking up little errors here and there as you write the .py files.

**Comment by SimonBiggs** [comment]
I like the thought process and the idea direction. But I do think it falls into the dangerous territory of creating two user interfaces to scriptedforms. One a markdown one, and one a notebook one. A problem which would be better served by having scriptedforms be able to read ipynb files directly.

But that division of input methods would complicate the code base and not actually allow more things to be created so although I like the idea I think it probably needs to be put to the side for now.
