### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#87]
Probably in your mind, but for deployment a docker image might be nice

**Comment by SimonBiggs** [comment]
At the moment I haven't even enabled use of a custom ip address. Currently scripted forms can only run on your local machine. It's a simple fix, but there are issues with allowing multiple users.

I'm also not sure what docker adds to this...

**Comment by robmarkcole** [comment]
Ideally we want this hosted on a central server, like I'm doing for jupyterhub at work. Then someone can create a form and send the URL for someone else to enter data. I understand this will add complexity, so perhaps put on the back burner.

Essentially, IT dept are so busy that they rely on me to advise how to deploy these kind of services. I'm familiar with Docker so suggested it but if theres a better way that's well documented then that's OK too

**Comment by SimonBiggs** [comment]
What if instead of docker, I work on making this a compatible Jupyter server extension. Which means it could run on the same jupyterhub server...

**Comment by SimonBiggs** [comment]
I'd be happy to provide the following next:

https://github.com/SimonBiggs/scriptedforms/issues/59

I really should refactor this into a jupyter notebook server extension. It opens many more useful options such as bundling it with jupyterhub.

**Comment by SimonBiggs** [comment]
Closed in favour of https://github.com/SimonBiggs/scriptedforms/issues/59
