### ISSUE TITLE
Document Security Model?

### ISSUE THREAD

**Issue by cathalgarvey** [SimonBiggs/scriptedforms#92]
Hi folks, I just came to your project, and looked at "HTML forms that execute Python", and immediately thought "NOPE"! :)

The reason for my concern was;

* I've never heard of a well-executed sandbox for securely running untrusted Python code
* I didn't see you mentioning any of the Python-in-browser-JS systems, like Brython, so I'm assuming the code is executed by the server somehow

I did take a quick peek to try and answer this question for myself, but found that the project is very large. I don't know where to look.

This indicates either a massive security problem, or (more likely) a minor documentation problem. How do I learn more about `scriptedforms`' security model, and how it prevents an attacker from executing malicious Python on the server?

Thanks!

**Comment by SimonBiggs** [comment]
@cathalgarvey thank you for your concern. This is built upon the Jupyter Notebook Server. They detail how the security works by default here:

http://jupyter-notebook.readthedocs.io/en/stable/security.html

And there is definitely more documentation on its way. Thanks for the reminder to leave a reference to the jupyter notebook security model.

**Comment by cathalgarvey** [comment]
So, if I understand this correctly, `scriptedforms` is designed with the following assumption in mind:

**Forms may only be filled-in by people we trust to execute arbitrary code on the hosting device**

..since Jupyter notebook server provides authentication to prevent outsiders executing code, and it includes UI protections against a trusted user accidentally executing code by opening a malicious notebook. But it doesn't include any protections against an untrusted user executing code sent to it by a trusted proxy (the form server).

So, imagine someone using this to create a little DIY polling booth, and letting anyone access it; depending on how they implemented things / locked down the device, and how `scriptedforms` sanitises inputs, there's a risk that an attacker could either put malicious inputs in to the form, or could create a malicious form POST to execute arbitrary code. If this is outside `scriptedforms`' security model, I think it should be documented.

**Comment by SimonBiggs** [comment]
Well currently, using scriptedforms cli it can only run as localhost.

**Comment by cathalgarvey** [comment]
That's good, but it still leaves "Kiosk" setups potentially vulnerable. Without security guidance, it's also possible for someone to manually bind it to a public IP without understanding the hazards that might pose.

**Comment by SimonBiggs** [comment]
As far as I am aware the jupyer notebook server under its default settings does not allow websocket access from any browser that does not come from the same origin as the localhost server. That should negate manually binding it to a public IP.

**Comment by SimonBiggs** [comment]
Anyway, I highly appreciate your concern. And if you can demonstrate an issue please do let me know. It is 12.30 am here in my timezone. :) I really better get to bed so that I can take the kids to preschool + the park tomorrow :).

Thank you again.

**Comment by SimonBiggs** [comment]
@blink1073 are you able to comment on this? Have I made a mistake in any of my understandings + assumptions?

**Comment by SimonBiggs** [comment]
@cathalgarvey I do agree with the "Kiosk" setup issue. I shall add a note to the front readme noting this issue.

**Comment by SimonBiggs** [comment]
@cathalgarvey would you agree that the following note addresses your concerns?

https://github.com/SimonBiggs/scriptedforms/blob/master/README.md#security-notice

**Comment by SimonBiggs** [comment]
I realised my comment about same origin was nonsense. I would be very interested to see what would happen should it be manually bound to another IP address. Either way, I think the main key is that I added a notice detailing that users of the form are not blocked from running arbitrary code.

Thank you.

**Comment by blink1073** [comment]
I agree with the updated readme.

**Comment by SimonBiggs** [comment]
Thanks Steven.

**Comment by SimonBiggs** [comment]
Can I just say, thank you @cathalgarvey. I foolishly overlooked the fact that given the simple set up people likely might not be aware of the jupyter notebook server and the associated security implications. 

I appreciate you bringing to my attention that people might try use something like this to host a website or create a kiosk and both of those cases would have dire security implications. Thank you.

**Comment by SimonBiggs** [comment]
Can this be closed since the addition to the front readme?

**Comment by robmarkcole** [comment]
Perhaps it could be admin configurable to use https://pypi.python.org/pypi/RestrictedPython ?

**Comment by SimonBiggs** [comment]
@robmarkcole my preference is to leave it as is. I doubt restricted python will be effective and reducing the arbitrary code execution abilities of the Jupyter Server. It can even execute cmd and bash code, not just Python.

I don't want to give any sense that an untrusted user should be let near it.

**Comment by cathalgarvey** [comment]
Hey @SimonBiggs - Sorry, I also had to dash yesterday, so I didn't get a chance to jump back in and comment. Thanks for adding the notice to the Readme, I think that clearly explains the security model to a new user. :)

Understanding the threat-model now, I can see myself using this for a few projects in the future. The uncertainty was what got me, at first. Thanks for your thoughtful answers here and the new documentation!
