### ISSUE TITLE
README example gives an error

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#96]
Following you example on the README with: 
```
<!-- markdownlint-disable MD033 -->

# An example

<section-start>

```python
%load_ext autoreload
%autoreload 1
%aimport example

# Normally you would just need to use the following:
# import example
```

</section-start>
<section-live>

<variable-slider>a_number</variable-slider>

```python
print('Your number is {}'.format(a_number))
```

</section-live>
``` 

I see: 

![image](https://user-images.githubusercontent.com/11855322/36716728-453b1ba8-1b93-11e8-912f-cab5389cfcc7.png)

**Comment by robmarkcole** [comment]
However when I run direct (`jupyter notebook --NotebookApp.default_url=/scriptedforms/robin.md`) I don't see the error:

![image](https://user-images.githubusercontent.com/11855322/36717016-50175bd0-1b94-11e8-8f19-b5911548b1e1.png)

**Comment by robmarkcole** [comment]
OK I also don't see when I restarted the lab (`jupyter lab`):

![image](https://user-images.githubusercontent.com/11855322/36717120-b2fc9a1c-1b94-11e8-8846-e681d96de60f.png)

**Comment by SimonBiggs** [comment]
I've noticed however that watchdog isn't working...

**Comment by robmarkcole** [comment]
Is watchdog really required - could you not just reload the script every second?

**Comment by SimonBiggs** [comment]
I'll get to the bottom of why it's not working. I imagine it was because there was too many subdirectories. I can make watchdog run quite a bit leaner.

**Comment by SimonBiggs** [comment]
That "an error occurred within python" probably needs the following imrovement:

https://github.com/SimonBiggs/scriptedforms/issues/98
